### ISSUE TITLE
High possibility of mixups

### ISSUE THREAD

**Issue by simskij** [jakowenko/watchtower#10]
Hi,

Just stumbled upon your project and thought I'd raise an issue. 

We've been running another project for a couple of years, which you might have heard of, at https://github.com/containrrr/watchtower. The scope is almost identical, as is the name, although written in go and without any telemetry. The risk for confusion, or users not realizing this is a totally separate project, is currently very high, especially as the package is available on NPM. 

Because of this, I'd kindly like to ask you if you'd be willing to change the name of your project and npm package to avoid mixups? Given that the functionality is somewhat similar, although you also send telemetry to your own server by default. The telemetry sent also possesses qualities that could enable vulnerability analysis of the host running the software.

It's in no way my intention to be rude or accusative, so I'm truly sorry if it comes across that way.

Thanks,
Simme

**Comment by jakowenko** [comment]
Hey @simskij, thanks for bringing this to my attention. I would be happy to update the README for this project to make it clear this is no way affiliated with containrrr/watchtower and to include more information about what telemetry information is passed.

**Comment by jakowenko** [comment]
Updated README to include a link to https://github.com/containrrr/watchtower, which this project was inspired by.
