### ISSUE TITLE
Option to ignore TLS for email notification

### ISSUE THREAD

**Issue by parker-hemphill** [jakowenko/watchtower#2]
I run bytemark/smtp container to act as a relay for my contarrr/watchtower image.  Trying yours but the email notifications won't work without something similar to watchtowers "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY" ENV variable

**Comment by jakowenko** [comment]
Latest build has ability to override this using the option `NOTIFY_EMAIL_IGNORE_TLS`. Let me know if this fixes your issue. Thank you!
